GET http://localhost:3000/coordinates/?building=1&startDate=2022-09-11 19:00:00&endDate=2022-09-19 20:00:00

###

POST http://localhost:3000/coordinates
Content-Type: application/json

{
    "building": 1,
    "latitude": 39.482445876265366,
    "longitude": -0.3464556142106639,
    "timestamp": "2022-09-15 12:00:00",
    "floorNumber": 1
}

###

GET http://localhost:3000/buildings

###
POST http://localhost:3000/buildings
Content-Type: application/json

{
    "name": "Test Building",
    "floors": 1,
    "latitude": 39.48067057885303,
    "longitude": -0.3398773008264785
}

###

PUT http://localhost:3000/buildings/2
Content-Type: application/json

{
    "name": "ETSINF - EDIFICIO 1E",
    "latitude": 39.482716712422764,
    "longitude": -0.346685476430633
}

###

DELETE http://localhost:3000/buildings/1