GET http://localhost:3000/coordinates/?building=1&startDate=2020-01-01 19:00:00&endDate=2022-12-30 20:00:00

###

POST http://localhost:3000/coordinates
Content-Type: application/json

{
    "building": 1,
    "floornumber": 2,
    "latitude": 39.482926395770775,
    "longitude": -0.3468272121410691,
    "timestamp": "2022-07-12 12:00:00"
}

###

GET http://localhost:3000/buildings

###
POST http://localhost:3000/buildings
Content-Type: application/json

{
    "name": "Test Building",
    "floors": 1,
    "latitude": 39.48067057885303,
    "longitude": -0.3398773008264785
}

###

PUT http://localhost:3000/buildings/7
Content-Type: application/json

{
    "name": "Test Building",
    "floors": 3,
    "latitude": 39.482716712422764,
    "longitude": -0.346685476430633
}

###

DELETE http://localhost:3000/buildings/1